# install.ps1 — install mstudio-dsh / kicad-auditor-dsh plugins on this machine.
# Two source modes:
#   A. Deployment bundle (pack.ps1 output, lib prebuilt): extract the zip and
#      run this script — default mode, no build toolchain required.
#   B. Source (after git pull): add -Build; needs a deepseek-harness checkout.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File .\install.ps1 `
#       [-MStudioDir <mstudio repo path>] [-KicadAuditorDir <kicad-auditor path>] `
#       [-ModusTemplateDir <firmware project path>] [-Build] [-SkipKicad]
#
# Path rules: omitted paths are auto-detected as siblings of this script.
param(
    [string]$MStudioDir = "",
    [string]$KicadAuditorDir = "",
    [string]$ModusTemplateDir = "",
    [string]$ProfileDir = "",
    [switch]$Build,
    [switch]$SkipKicad
)

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# ── 0. detect mode and repo locations ───────────────────────────────────────
$packMode = Test-Path (Join-Path $scriptDir "mstudio-dsh")
$sourceMode = Test-Path (Join-Path $scriptDir "package.json")

if ($packMode) {
    Write-Host "[MODE] bundle install (lib prebuilt, no build)" -ForegroundColor Cyan
} elseif ($sourceMode) {
    Write-Host "[MODE] source install" -ForegroundColor Cyan
} else {
    Write-Host "[ERROR] Cannot recognize run location: need bundle content (mstudio-dsh/) or source (package.json)." -ForegroundColor Red
    exit 1
}

if ($sourceMode) {
    $mstudioPkg = $scriptDir
    if (-not $MStudioDir) { $MStudioDir = Split-Path -Parent $mstudioPkg }
}
# probe kicad-auditor as a sibling of mstudio (or of this script in bundle mode)
if (-not $KicadAuditorDir) {
    $base = if ($MStudioDir) { Split-Path -Parent $MStudioDir } else { Split-Path -Parent $scriptDir }
    $cand = Join-Path $base "kicad-auditor"
    if (Test-Path $cand) { $KicadAuditorDir = $cand }
}
if (-not $KicadAuditorDir -and -not $SkipKicad) {
    Write-Host "[WARN] kicad-auditor repo not found; kicad plugin will NOT be mounted (or pass -KicadAuditorDir)" -ForegroundColor Yellow
    $SkipKicad = $true
}

# ── 1. build (only with -Build) ─────────────────────────────────────────────
if ($Build) {
    $tsc = Join-Path $MStudioDir "..\deepseek-harness\node_modules\.bin\tsc.cmd"
    if (-not (Test-Path $tsc)) {
        Write-Host "[ERROR] -Build needs deepseek-harness source as sibling of mstudio with pnpm install: $tsc" -ForegroundColor Red
        exit 1
    }
    function Invoke-Build { param([string]$pkg, [string]$label)
        Write-Host "[BUILD] $label ..." -ForegroundColor Cyan
        Push-Location $pkg
        Remove-Item lib -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item tsconfig.tsbuildinfo -Force -ErrorAction SilentlyContinue
        & $tsc -p tsconfig.json --incremental false
        if ($LASTEXITCODE -ne 0) { Write-Host "[ERROR] $label build failed" -ForegroundColor Red; Pop-Location; exit 1 }
        Pop-Location
    }
    Invoke-Build $scriptDir "mstudio-dsh"
    if (-not $SkipKicad) { Invoke-Build (Join-Path $KicadAuditorDir "dsh-integration") "kicad-auditor-dsh" }
}

# ── 2. locate DSH profile ───────────────────────────────────────────────────
if (-not $ProfileDir) { $ProfileDir = Join-Path $env:USERPROFILE ".dsh\profiles\web" }
$wxDir = Join-Path $ProfileDir "node_modules\@wx"
if (-not (Test-Path $ProfileDir)) {
    Write-Host "[ERROR] DSH profile not found: $ProfileDir (run DSH web once first)" -ForegroundColor Red
    exit 1
}
New-Item -ItemType Directory -Path $wxDir -Force | Out-Null

# ── 3. deploy plugins ────────────────────────────────────────────────────────
function Install-Pkg { param([string]$name, [string]$libSrc)
    $dest = Join-Path $wxDir $name
    Remove-Item $dest -Recurse -Force -ErrorAction SilentlyContinue
    Copy-Item $libSrc -Destination "$dest\lib" -Recurse -Force
    Write-Host "[OK] deployed $name" -ForegroundColor Green
}
Install-Pkg "mstudio-dsh" "$scriptDir\mstudio-dsh\lib"
if (-not $SkipKicad) { Install-Pkg "kicad-auditor-dsh" "$scriptDir\kicad-auditor-dsh\lib" }

# ── 4. generate/update profile patch with machine-local paths ───────────────
if (-not $ModusTemplateDir -and $MStudioDir) {
    $cand = Join-Path (Split-Path -Parent $MStudioDir) "modus_template"
    if (Test-Path $cand) { $ModusTemplateDir = $cand }
}
$patchFile = Join-Path $ProfileDir "cordis.patch.yml"
$patchBegin = "# >>> mstudio-dsh managed block >>>"
$patchEnd = "# <<< mstudio-dsh managed block <<<"

function Get-ManagedBlock {
    $lines = @(
        "# >>> mstudio-dsh managed block >>>",
        "# Auto-generated by install.ps1; replaced wholesale on reinstall. Move manual edits outside this block.",
        "- insert:",
        "    - id: mstudio-aitrace",
        "      name: '@wx/mstudio-dsh'",
        "      config:",
        "        workDir: $($ModusTemplateDir -replace '\\','/')",
        "        aitracePath: tools/aitrace.exe",
        "        elfPath: build/template.elf",
        "        mapPath: build/template.map",
        "        captureDir: captures",
        "        approval: true"
    )
    if (-not $SkipKicad) {
        $lines += @(
            "    - id: kicad-auditor-dsh",
            "      name: '@wx/kicad-auditor-dsh'",
            "      config:",
            "        workDir: $($KicadAuditorDir -replace '\\','/')",
            "        auditorPath: $((Join-Path $KicadAuditorDir 'kicad-auditor.exe') -replace '\\','/')"
        )
    }
    $lines += "# <<< mstudio-dsh managed block <<<"
    return ($lines -join "`r`n")
}

$block = Get-ManagedBlock
$utf8Bom = New-Object System.Text.UTF8Encoding($true)

if (Test-Path $patchFile) {
    $content = [System.IO.File]::ReadAllText($patchFile, $utf8Bom)
    if ($content.Contains($patchBegin)) {
        $pattern = "(?s)$([regex]::Escape($patchBegin)).*?$([regex]::Escape($patchEnd))"
        $content = [regex]::Replace($content, $pattern, $block)
    } else {
        $content = $content.TrimEnd() + "`r`n`r`n" + $block
    }
    [System.IO.File]::WriteAllText($patchFile, $content, $utf8Bom)
} else {
    [System.IO.File]::WriteAllText($patchFile, $block, $utf8Bom)
}
Write-Host "[OK] profile patch updated: $patchFile" -ForegroundColor Green

# ── 5. install skills from repo copies ───────────────────────────────────────
$agentsSkills = Join-Path $env:USERPROFILE ".agents\skills"
New-Item -ItemType Directory -Path $agentsSkills -Force | Out-Null
foreach ($skillDir in @("$scriptDir\skills\kicad-auditor", "$scriptDir\skills\aitrace")) {
    if (Test-Path $skillDir) {
        $name = Split-Path -Leaf $skillDir
        $dest = Join-Path $agentsSkills $name
        Remove-Item $dest -Recurse -Force -ErrorAction SilentlyContinue
        Copy-Item $skillDir -Destination $dest -Recurse -Force
        Write-Host "[OK] skill installed: $name" -ForegroundColor Green
    }
}

# ── 6. toolchain check ──────────────────────────────────────────────────────
Write-Host ""
Write-Host "===== toolchain check =====" -ForegroundColor Cyan
$checks = @()
if (Test-Path "$wxDir\mstudio-dsh\lib\index.js") { $checks += "[OK] mstudio-dsh plugin in place" } else { $checks += "[!!] mstudio-dsh plugin MISSING" }
if (-not $SkipKicad) {
    if (Test-Path "$wxDir\kicad-auditor-dsh\lib\index.js") { $checks += "[OK] kicad-auditor-dsh plugin in place" } else { $checks += "[!!] kicad-auditor-dsh plugin MISSING" }
}
if (Test-Path "$env:USERPROFILE\.agents\skills\kicad-auditor\SKILL.md") { $checks += "[OK] skill: kicad-auditor" } else { $checks += "[!!] skill: kicad-auditor MISSING" }
if (Test-Path "$env:USERPROFILE\.agents\skills\aitrace\SKILL.md") { $checks += "[OK] skill: aitrace" } else { $checks += "[!!] skill: aitrace MISSING" }
$gpp = Get-Command g++ -ErrorAction SilentlyContinue
if ($gpp) { $checks += "[OK] g++ ($($gpp.Source))" } else { $checks += "[!!] g++ not on PATH (MSYS2 needed to build kicad-auditor.exe)" }
if (-not $SkipKicad -and $KicadAuditorDir) {
    if (Test-Path (Join-Path $KicadAuditorDir "kicad-auditor.exe")) { $checks += "[OK] kicad-auditor.exe built" } else { $checks += "[!!] kicad-auditor.exe MISSING (run make.bat in kicad-auditor)" }
}
$checks | ForEach-Object { Write-Host $_ }
Write-Host ""
Write-Host "[NOTE] aitrace.exe: build from mstudio source (build.bat) or copy the binary."
Write-Host "       KiCad Huaqiu, OpenOCD and probe drivers: install as needed."
Write-Host "       Restart DSH Web GUI to load the plugins."
